name: Build LaTeX document
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            main.tex
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: main.pdf # Same base name as the .tex file
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
